# Generated by Django 3.0.3 on 2020-02-15 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='title',
        ),
    ]
