# Generated by Django 3.0.3 on 2020-02-18 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_course_coursesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'verbose_name': 'Course Section', 'verbose_name_plural': 'Course Sections'},
        ),
    ]
