# Generated by Django 3.0.3 on 2020-02-19 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_auto_20200217_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseAbbrev',
            field=models.CharField(default='DEFAULT', max_length=128),
        ),
        migrations.AddField(
            model_name='course',
            name='courseValue',
            field=models.CharField(default='12345', max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
