# Generated by Django 3.0.3 on 2020-02-20 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0005_auto_20200219_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RenameField(
            model_name='coursesection',
            old_name='course',
            new_name='currentCourse',
        ),
        migrations.AlterField(
            model_name='course',
            name='courseAbbrev',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseValue',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.CreateModel(
            name='CourseMeetingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetType', models.CharField(max_length=3)),
                ('meetDates', models.CharField(max_length=7)),
                ('meetStartTime', models.CharField(max_length=7)),
                ('meetEndTime', models.CharField(max_length=7)),
                ('meetSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.CourseSection')),
            ],
            options={
                'verbose_name': 'Course Meeting Time',
                'verbose_name_plural': 'Course Meeting Times',
            },
        ),
    ]
