# Generated by Django 3.0.3 on 2020-02-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0006_auto_20200220_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursesection',
            name='instructorName',
        ),
        migrations.AddField(
            model_name='coursemeetingtime',
            name='meetInstructor',
            field=models.CharField(default='', max_length=128),
        ),
    ]
