# Generated by Django 3.0.3 on 2020-03-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0007_auto_20200220_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pName', models.CharField(max_length=128)),
                ('pEmail', models.CharField(max_length=128)),
                ('currentCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Course')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='TeachingAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tName', models.CharField(max_length=128)),
                ('tEmail', models.CharField(max_length=128)),
                ('currentCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Course')),
            ],
            options={
                'verbose_name': 'Teaching Assistant',
                'verbose_name_plural': 'Teaching Assistants',
            },
        ),
        migrations.AlterField(
            model_name='coursemeetingtime',
            name='meetSection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courseMeetingTimes', to='scrape.CourseSection'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='currentCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scrape.Course'),
        ),
        migrations.CreateModel(
            name='TeachingAssistantOfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetStartTime', models.CharField(max_length=7)),
                ('meetEndTime', models.CharField(max_length=7)),
                ('meetLocation', models.CharField(max_length=23)),
                ('meetDates', models.CharField(max_length=7)),
                ('meetTA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.TeachingAssistant')),
            ],
            options={
                'verbose_name': 'Teaching Assistant Office Hours',
            },
        ),
        migrations.CreateModel(
            name='ProfessorOfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetStartTime', models.CharField(max_length=7)),
                ('meetEndTime', models.CharField(max_length=7)),
                ('meetLocation', models.CharField(max_length=23)),
                ('meetDates', models.CharField(max_length=7)),
                ('meetProfessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Professor')),
            ],
            options={
                'verbose_name': 'Professor Office Hours',
            },
        ),
    ]
