# Generated by Django 3.0.3 on 2020-03-05 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0008_auto_20200305_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorofficehours',
            options={'verbose_name': 'Professor Office Hour', 'verbose_name_plural': 'Professor Office Hours'},
        ),
    ]
