# Generated by Django 3.0.3 on 2020-03-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0009_auto_20200305_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingassistantofficehours',
            options={'verbose_name': 'Teaching Assistant Office Hour', 'verbose_name_plural': 'Teaching Assistant Office Hours'},
        ),
    ]
