# Generated by Django 3.0.3 on 2020-03-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_auto_20200305_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iType', models.CharField(max_length=1)),
                ('iName', models.CharField(max_length=128)),
                ('iEmail', models.CharField(max_length=128)),
                ('currentCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Course')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructor',
            },
        ),
        migrations.CreateModel(
            name='InstructorOfficeHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetStartTime', models.CharField(max_length=7)),
                ('meetEndTime', models.CharField(max_length=7)),
                ('meetLocation', models.CharField(max_length=23)),
                ('meetDates', models.CharField(max_length=7)),
                ('meetInstructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Instructor')),
            ],
            options={
                'verbose_name': 'Instructor Office Hour',
                'verbose_name_plural': 'Instructor Office Hours',
            },
        ),
        migrations.RemoveField(
            model_name='professorofficehours',
            name='meetProfessor',
        ),
        migrations.RemoveField(
            model_name='teachingassistant',
            name='currentCourse',
        ),
        migrations.RemoveField(
            model_name='teachingassistantofficehours',
            name='meetTA',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='ProfessorOfficeHours',
        ),
        migrations.DeleteModel(
            name='TeachingAssistant',
        ),
        migrations.DeleteModel(
            name='TeachingAssistantOfficeHours',
        ),
    ]
