# Generated by Django 3.0.3 on 2020-03-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0010_auto_20200305_2118'),
        ('scrape', '0008_auto_20200303_1947'),
    ]

    operations = [
    ]
