# Generated by Django 3.0.3 on 2020-03-28 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0011_auto_20200328_1732'),
        ('scrape', '0008_auto_20200303_1947'),
    ]

    operations = [
    ]
