# Generated by Django 3.0.3 on 2020-03-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0011_merge_20200326_1520'),
        ('scrape', '0013_auto_20200328_2049'),
    ]

    operations = [
    ]
