# Generated by Django 3.0.3 on 2020-03-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('meetInstructor', models.CharField(max_length=50)),
                ('meetStartTime', models.CharField(max_length=7)),
                ('meetEndTime', models.CharField(max_length=7)),
                ('meetLocation', models.CharField(max_length=23)),
                ('meetDates', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'User Schedule Item',
                'verbose_name_plural': 'User Schedule Items',
            },
        ),
    ]
