# Generated by Django 3.0.3 on 2020-03-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'User Schedule',
                'verbose_name_plural': 'User Schedules',
            },
        ),
    ]
