# Generated by Django 3.0.3 on 2020-04-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_userschedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscheduleitem',
            name='username',
        ),
    ]
