# Generated by Django 3.0.5 on 2020-04-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_remove_userscheduleitem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscheduleitem',
            name='meetCourseName',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
